### ISSUE TITLE
setup pylint

### ISSUE THREAD

**Issue by joegasewicz** [joegasewicz/pytask-io#13]
setup pylint

**Comment by Kishore-abhimanyu** [comment]
can you assign me this?

**Comment by joegasewicz** [comment]
It's all yours @Kishore-abhimanyu thanks you.

**Comment by Kishore-abhimanyu** [comment]
can you please explain this, because pylint is already configured, do you want to fix those issues?

**Comment by joegasewicz** [comment]
@Kishore-abhimanyu Can you adjust the `.pylintrc` file to run `pylint` command and make sure the existing code passes. If it fails then fix the `.pylintrc` file to make the code pass. We do not want to change any code yet, thanks.
