### ISSUE TITLE
Fix `test_add_task` tests

### ISSUE THREAD

**Issue by joegasewicz** [joegasewicz/pytask-io#24]
Looks like this tests needs fixing..
https://github.com/joegasewicz/pytask_io/blob/1921fc4b0aee177a6974492d6340128afbaab42e/tests/test_pytask_io.py#L55

**Comment by manan2002** [comment]
Hey! Can I work on It?

**Comment by joegasewicz** [comment]
@manan2002 Of course you can haha thanks.

**Comment by joegasewicz** [comment]
@manan2002 Let me know which tests you wish to work on, and ill open issues up for each other broken test, there are 4 in total, thanks.

**Comment by manan2002** [comment]
@joegasewicz could you please list out which one are broken?

**Comment by joegasewicz** [comment]
@manan2002 Ive updated the title to target the broken unit test:

https://github.com/joegasewicz/pytask_io/blob/1921fc4b0aee177a6974492d6340128afbaab42e/tests/test_pytask_io.py#L55

thanks @manan2002

**Comment by manan2002** [comment]
Thanks, I'll get to it.

**Comment by MakuZo** [comment]
This is probably fixed
