### ISSUE TITLE
stop() method blocks main thread forever

### ISSUE THREAD

**Issue by MakuZo** [joegasewicz/pytask-io#58]
Steps to reproduce:
```
>>> from pytask_io import PyTaskIO
>>> pytask = PyTaskIO()
>>> pytask.run()
>>> pytask.stop()
```

**Comment by joegasewicz** [comment]
This still needs working on, assigning to me ...

**Comment by joegasewicz** [comment]
This solution seems to be  the right approach.
I need to also fix any unit tests, and test any bugs but very pleased with this!

**Comment by joegasewicz** [comment]
https://github.com/joegasewicz/pytask-io/pull/64
