### ISSUE TITLE
Check to see if main loop attribute has been created before referencing

### ISSUE THREAD

**Issue by joegasewicz** [joegasewicz/pytask-io#61]
Check to see if main loop attribute has been created before referencing,
otherwise an AttributeError is thrown

**Comment by joegasewicz** [comment]
@MakuZo can you re open this please so I can cherry pick the exception & test work which looked excellent, thank you

**Comment by MakuZo** [comment]
@joegasewicz Done https://github.com/joegasewicz/pytask-io/pull/62
