### ISSUE TITLE
Allow users of this library to choose between a Redis store & in memory

### ISSUE THREAD

**Issue by joegasewicz** [joegasewicz/pytask-io#8]
Allow users of this library to choose between a Redis store & in memory

**Comment by MakuZo** [comment]
This would require writing a memory storage first, right?

**Comment by joegasewicz** [comment]
hey @MakuZo Sorry this is being closed as the task would be too big, to implement a shared storage library across multiple processes / networks .. better to use existing solutions such as Redis
